modules/Cms/Http/routes.php
<?php

Route::group(['middleware' => ['web','auth'], 'prefix' => 'dashboard', 'namespace' => 'Modules\Cms\Http\Controllers'], function()
{
	
	Route::get('/', 'DashboardController@index')->name('dashboard');
	Route::post('/', 'DashboardController@settingUpdate')->name('dashboard.setting.update');

	// Route::get('/category', ['uses' => 'CategoryController@index', 'as' => 'dashboard.category.index']);
	// Route::get('/category/create', ['uses' => 'CategoryController@create', 'as' => 'dashboard.category.create']);
	// Route::get('/category/edit', ['uses' => 'CategoryController@edit', 'as' => 'dashboard.category.edit']);
	// Route::get('/category/destroy', ['uses' => 'CategoryController@destroy', 'as' => 'dashboard.category.destroy']);
	
	Route::resource('category', 'CategoryController', ['except' => ['show']]);

	Route::get('post/{post}/copy', 'PostController@copy')->name('dashboard.post.copy');
	Route::resource('post', 'PostController', ['except' => ['show']]);

	Route::get('blog/{blog}/copy', 'BlogController@copy')->name('dashboard.blog.copy');
	Route::resource('blog', 'BlogController', ['except' => ['show']]);

	Route::get('menu/order', 'MenuController@order')->name('dashboard.menu.order');
	Route::get('menu/footer', 'MenuController@footerindex')->name('dashboard.menu.footer.index');
	Route::post('menu/footer', 'MenuController@footerstore')->name('dashboard.menu.footer.store');
	Route::get('menu/footer/create', 'MenuController@footercreate')->name('dashboard.menu.footer.create');
	Route::resource('menu', 'MenuController', ['except' => ['show']]);

});

modules/Cms/Http/Controllers/BlogController.php
<?php namespace Modules\Cms\Http\Controllers;

use Pingpong\Modules\Routing\Controller;

use Modules\Cms\Entities\Category;
use Modules\Cms\Entities\Post;
use Illuminate\Foundation\Auth\User;

use Illuminate\Support\Facades\View;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Redirect;
use Validator;
use DB;

use Breadcrumbs;
use Modules\Cms\Http\Controllers\DashboardController;

class BlogController extends DashboardController {
	

    public function __construct(){
        parent::__construct();
        // to solve php artisan route:list error
        // error : Breadcrumb name "dashboard.blog.index" has already been registered
        if (! Breadcrumbs::exists('dashboard.blog.index')) {    
            Breadcrumbs::register('dashboard.blog.index', function($breadcrumbs)
            {
                $breadcrumbs->parent('dashboard');
                $breadcrumbs->push('Blog', route('dashboard.blog.index'));
            });
        }
        DB::enableQueryLog();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = User::All();  

        $query = Post::where(Post::$table_name.'.published',1);
        $query = $query->whereIn('type', array_values(get_blog_types()));
        if (\Request::get('author_id')) {
          $query = $query->leftJoin(Category::$table_name, Post::$table_name.'.author_id', '=', 'users.id')
                        ->where(Post::$table_name.'.author_id', \Request::get('author_id'));
        }
        if (\Request::get('title')) {
          $query = $query->where(Post::$table_name.'.title', 'like', \Request::get('title').'%');;
        }
        $query = $query->addSelect(Post::$table_name.'.*');
        $query = $query->orderBy(Post::$table_name.'.id', 'desc');
        
        $blogs = $query->paginate(10);

        return View::make('cms::blog.backend.index' , compact('blogs', 'users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $blog_types = get_blog_types();  

        $blog = new post();
        Breadcrumbs::register('dashboard.blog.create', function($breadcrumbs)
        {
            $breadcrumbs->parent('dashboard.blog.index');
            $breadcrumbs->push('Create', route('dashboard.blog.create'));
        });
        return View::make('cms::Blog.backend.create' , compact('blog', 'blog_types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
     
        // validate
        $rules =  array(
            'title' => 'required|max:255',
            'content' => 'required|max:5000',
            );

        $validator = Validator::make(Input::all(), $rules);

        if ($validator->fails()) {
            Session::flash('error', 'Creation failed!');
            return Redirect::route('dashboard.blog.create')->withErrors($validator->errors());
        } else {

            $data = request()->all();

            $blog_category = get_blog_category();
            $data['category_id'] = $blog_category->id;

            $data['author_id'] = auth()->id();
            $data['slug'] = str_slug(Input::get('title'));

            $data = $this->update_blog_data($data);

            Post::create($data);
            
            // redirect
            Session::flash('success', 'Successfully created!');
            return Redirect::route('dashboard.blog.index');
        }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $blog_types = get_blog_types();  

        // get the Blog
        $blog = Post::find($id);
        if(!$blog){
            Session::flash('error', 'Blog not found');
            return Redirect::route('dashboard.blog.index');
        }

        Breadcrumbs::register('dashboard.blog.edit', function($breadcrumbs)
        {
            $breadcrumbs->parent('dashboard.blog.index');
            $breadcrumbs->push('Edit');
        });

        if($blog->type == get_blog_types('GALLERY')){
          // show the edit form and pass the Blog
          $images = json_encode(unserialize($blog->images));          
        }

        return View::make('cms::Blog.backend.update' , compact('blog', 'blog_types', 'images'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // validate
        $rules =  [
            'title' => 'required|max:255',
            'content' => 'required|max:5000',
        ];

        $validator = Validator::make(Input::all(), $rules);

        if ($validator->fails()) {
            Session::flash('error', 'Update failed!');
            return Redirect::route('dashboard.blog.edit', $id)->withErrors($validator->errors());
        } else {

            // update
            $blog = Post::find($id);
            $data = request()->all();
            
            $data = $this->update_blog_data($data);
            
            $blog->update($data);

            // redirect
            Session::flash('success', 'Successfully updated!');
            return Redirect::route('dashboard.blog.edit', $id);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // delete
        $blog = Post::find($id);
        $blog->delete();

        // redirect
        Session::flash('success', 'Successfully deleted!');
        return Redirect::route('dashboard.blog.index');
    }

    /**
     * Handle Method does not exist.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function copy($id){
        // get the Blog
        $blog = Post::find($id);
        if(!$blog){
            Session::flash('error', 'Blog not found');
            return Redirect::route('dashboard.blog.index');
        }

        Breadcrumbs::register('dashboard.blog.edit', function($breadcrumbs)
        {
            $breadcrumbs->parent('dashboard.blog.index');
            $breadcrumbs->push('Edit');
        });

        $blog = $blog->replicate(); //copy attributes
        $blog->slug = rand(1,500); 
        $blog->save(); 

        // redirect
        Session::flash('success', "Successfully Copied (with slug={$blog->slug}) !");
        return Redirect::route('dashboard.blog.index');

    }

    /**
     * [update_blog_data as per blog type]
     * @param  array $data
     * @return array      
     */
    private function update_blog_data($data){

      if($data['type'] == get_blog_types('IMAGE')){ 
        $data['video'] = $data['images'] = '';              
      }elseif($data['type'] == get_blog_types('VIDEO')){               
        $data['featured_image'] = $data['images'] = '';              
      }elseif($data['type'] == get_blog_types('GALLERY')){               
        $data['featured_image'] = $data['video'] = '';
        if(isset($data['images'])){
          $data['images'] = serialize($data['images']);
        }              
      }

      return $data;
    }
}

modules/Cms/Resources/views/blog/backend/create.blade.php
@extends('backend.layout')

@section('title', 'Create Blog')

@section('content')

<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">Create Blog</h3>				
			</div>
			<!-- /.box-header -->

			<div class="box-body no-padding">

				{{ Form::model($blog, array('route' => array('dashboard.blog.store'))) }}       

					<span class="col-md-4 col-lg-4">
					<div class="form-group">
						<!-- title -->
						{{ Form::label('title', 'Title') }}
						{{ Form::text('title', null , array( 'class' => 'form-control' ) ) }}      
					</div>
					</span>

					<span class="col-md-4 col-lg-4">
					<div class="form-group">
						<!-- type -->						
						{{ Form::label('type', 'Type') }}
						{!! Form::select('type', $blog_types, null , array( 'class' => 'form-control', 'id' => 'blog_type' )) !!}
						</div>					
					</span>

					<span class="col-md-4 col-lg-4">
					<div class="form-group">
						<!-- url -->
						{{ Form::label('url', 'Url') }}
						{{ Form::text('url', null , array( 'class' => 'form-control', 'placeholder' => '/aboutus' ) ) }}      
					</div>					
					</span>

					<span class="col-md-12 col-lg-12">
					<div class="form-group">
						<!-- content -->
						{{ Form::label('content', 'Content') }}
						{{ Form::textarea('content', null, array( 'class' => 'form-control', 'id' => 'mytextarea' ) ) }}
					</div>
					</span>

				<span class="col-md-6 col-lg-6">

					<p>
					  <h5>Meta Info.</h5> 
					  <div class="form-group">
						<!-- meta_desc -->
						{{ Form::label('meta_desc', 'Meta description') }}
						{{ Form::text('meta_desc', null, array( 'class' => 'form-control' ) ) }}
					  </div> 
					  <div class="form-group">
						<!-- meta_key -->
						{{ Form::label('meta_key', 'Meta keywords') }}
						{{ Form::text('meta_key', null, array( 'class' => 'form-control' ) ) }}
					  </div> 
					  <div class="form-group">
						<!-- meta_robot -->
						{{ Form::label('meta_robot', 'Meta robots') }}
						{{ Form::text('meta_robot', null, array( 'class' => 'form-control' ) ) }}
					  </div> 
					</p>
				</span>

				<span class="col-md-6 col-lg-6">
					
					<span class="blog_type_image">
					  <h5>Image Info.</h5>          
					  <div class="form-group">
						<!-- featured_image_title -->
						{{ Form::label('featured_image_title', 'Image title') }}
						{{ Form::text('featured_image_title', null, array( 'class' => 'form-control' ) ) }}
					  </div> 
					  <div class="form-group">

						<!-- featured_image -->
						{{ Form::label('Image', 'Image') }}

						<div class="input-group">
						<span class="input-group-btn">
						 <a id="lfm-image" data-input="thumbnail-image" data-preview="holder-image" class="btn btn-primary">
						   <i class="fa fa-picture-o"></i> Choose
						 </a>
						</span>
						{{ Form::hidden('featured_image', null, array( 'class' => 'form-control', 'id' => 'thumbnail-image' ) ) }}
						</div>
						<img id="holder-image" style="margin-top:15px;max-height:100px;" 
						<?php echo $blog->featured_image ? "src='".url($blog->featured_image)."'": '';?>>
					  </div>
					</span>

					<span class="blog_type_video" hidden>
					  <h5>Video Info.</h5>          


						<div class="form-group">
						<!-- vdo_title -->
						{{ Form::label('video_title', 'Video title') }}
						{{ Form::text('video_title', null, array( 'class' => 'form-control' ) ) }}
						</div> 

					  <div class="form-group">

						<!-- featured_image -->
						{{ Form::label('Video', 'Video') }}

						<div class="input-group">
						<span class="input-group-btn">
						 <a id="lfm-video" data-input="thumbnail-video" data-preview="holder-video" class="btn btn-primary">
						   <i class="fa fa-picture-o"></i> Choose
						 </a>
						</span>
						{{ Form::text('video', null, array( 'class' => 'form-control', 'id' => 'thumbnail-video') ) }}
						</div>
						<iframe id="holder-video" style="margin-top:15px;max-height:100px;" 
						<?php echo $blog->video ? "src='".url($blog->video)."'": '';?> 
						frameborder="0" class="video_preview" width="320" height="240"></iframe>

					  </div>
					  	
					  <div class="form-group">
						OR 
						<!-- video_url -->
						{{ Form::label('video_url', 'Video url') }}
						{{ Form::text('video_url', null, array( 'class' => 'form-control' ) ) }}

						<video width="320" height="240" style="margin-top:15px;max-height:100px;" controls>
						  <source src="<?php echo $blog->video_url ? : '';?>" type="video/mp4">
						  <source src="<?php echo $blog->video_url ? : '';?>" type="video/webm">
						  <source src="<?php echo $blog->video_url ? : '';?>" type="video/ogg">
						  Your browser does not support the video tag.
						</video>

					  </div>
					  	
					  <div class="form-group">
						OR <!-- video_embed -->
						{{ Form::label('video_embed', 'Video Embed') }}
						{{ Form::textarea('video_embed', null, array( 'class' => 'form-control', 'rows' => '3') ) }}
						<?php echo $blog->video_embed ? : '';?> 
					  </div>					  
					</span>   

					<span class="blog_type_gallery" hidden>
					  <h5>Image Info.</h5>          
					  <div class="form-group">

						<!-- featured_image -->
						{{ Form::label('Gallery Image', 'Gallery Image') }}

						<div class="input-group">
						<span class="input-group-btn">
						 <a id="lfm-image-gallery" data-input="thumbnail-image" data-preview="holder-image-gallery" class="btn btn-primary">
						   <i class="fa fa-picture-o"></i> Choose More
						 </a>
						</span>
						</div>
						

					  </div>
					</span>
				</span>

			</div>

			<!-- /.box-body -->
			<div class="box-footer clearfix">
				{{ Form::submit('Save', array( 'class' => 'btn btn-primary' )) }}
				{{ Form::close() }}
				<a href=" {{ route( 'dashboard.post.index' ) }}" class="btn btn-default"/>Cancel</a>				
			</div>

		</div>
		<!-- /.box -->
	</div>
</div>
<script type="text/javascript">
	var blog_edit_or_create = true;
</script>
@endsection

modules/Cms/Resources/views/blog/backend/index.blade.php
@extends('backend.layout')

@section('title', 'Blogs')

@section('content')

<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">Blogs</h3>
				<span class="pull-right">
					<a href="{{ route('dashboard.blog.create') }}" title="Create">
						<button type="button" class="btn btn-primary"><i class="fa fa-plus"></i></button>
					</a>
				</span>

				<form action="" method="GET" role="form">
					<table class="table filter">            
						<tbody>
							<tr>
								<td class="col-lg-3">
									<div class="form-group">
										<label>Author</label>
										<select id="author_id" class="form-control" name="author_id">
											<option value="">Select</option>
											@foreach($users as $user)
												<option value="{{ $user->id }}"
													@if ( \Request::get('author_id') == $user->id ) 
														selected 
													@endif
													/>
													{{ $user->name }}
												</option>
											} ?>
											@endforeach
										</select>
									</div>
								</td>
								<td class="col-lg-3">
									<div class="form-group">
										<label>Blog Title</label>
										<div class="controls">
											<input type="text" name="title" id="title"  data-required="1" 
											class="form-control" placeholder="Blog Title here"
											value="{{ \Request::get('title') }}">
										</div>
									</div>
								</td>
								<td class="col-lg-3">
									<div class="form-group pull-right">
										<br>
										<br>
										<div class="controls">
											<input type="submit" class="btn btn-info" name="filter" value="Filter">
											<a href=" {{ route( 'dashboard.blog.index' ) }}" class="btn btn-default">Reset</a>
										</div>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
				</form>

			</div>
			<!-- /.box-header -->
			<div class="box-body">

				<table class="table table-bordered">
					<tbody>
						<tr>
							<th style="width: 10px">#</th>
							<th>Title</th>
							<th>Type</th>
							<th>Created At</th>
							<th>Actions</th>
						</tr>

						@if( count($blogs) > 0 )
						@foreach($blogs as $blog)
						<tr>
							<td>{{ $blog->id }}</td>
							<td>
								{{ $blog->title }}
								<br>
								-- <i>by : {{ $blog->author->name }}</i> -- 
							</td>
							
							<td>
								<?php 
									if($blog->type){
										$html = '';
										switch ($blog->type) {
											case get_blog_types('IMAGE'):
												if($blog->featured_image){
													echo "<img src='".url($blog->featured_image)."' class='img-responsive' width='200px' height='150px' title='{$blog->featured_image_title}'>";
												}
												break;
											case get_blog_types('VIDEO'):
												if(trim($blog->video)){
													echo "<iframe src='".url($blog->video)."'  width='200px' height='150px' title='{$blog->video_title}'></iframe>";
												}elseif (trim($blog->video_url)) {
													?>
													<video width="320" height="240" style="margin-top:15px;max-height:100px;" controls>
													  <source src="<?php echo $blog->video_url ? : '';?>" type="video/mp4">
													  <source src="<?php echo $blog->video_url ? : '';?>" type="video/webm">
													  <source src="<?php echo $blog->video_url ? : '';?>" type="video/ogg">
													  Your browser does not support the video tag.
													</video>
													<?php
												}elseif (trim($blog->video_embed)) {
													echo $blog->video_embed;
												}
												break;
											case get_blog_types('GALLERY'):
												if($blog->images){
												  $images = $unserialized = unserialize($blog->images);
												  if($unserialized !== false && count($images)>0){
												    ?>
												    <div id="carousel-example-generic" class="carousel slide" style="max-width:200px; max-height:150px;" data-ride="carousel">

												        <ol class="carousel-indicators">
												            <?php foreach ($images as $key => $image) { ?>
												                <li data-target="#carousel-example-generic" data-slide-to="<?php echo $key?>" class="<?php echo $key==0?'active':''?>"></li>
												                <?php 
												            } ?>
												        </ol>

												        <div class="carousel-inner">
												            <?php foreach ($images as $key => $image) { ?>
												                <div class="item <?php echo $key==0?'active':''?>">
												                    <img src="<?php echo url($image)?>">
												                </div>
												                <?php 
												            } ?>                                                    
												        </div>

												        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
												            <span class="fa fa-angle-left"></span>
												        </a>

												        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
												            <span class="fa fa-angle-right"></span>
												        </a>
												    </div>
												    <?php 
													}
												}																							
												break;											
										}
										echo "<br>";
										echo get_blog_types($blog->type); 
									}
								?>
							</td>
							<td>{{ $blog->created_at }}</td>
							<td>													

								<a href=" {{ route( 'dashboard.blog.edit' , $blog->id ) }} " class="btn btn-default fa fa-pencil" data-toggle="tooltip" data-original-title="Edit"></a>

								<a href=" {{ route( 'dashboard.blog.copy' , $blog->id ) }} " class="btn btn-sm btn-icon add-tooltip btn-default fa fa-copy" data-toggle="tooltip" data-original-title="Copy"></a>

								{!! Form::open(array(
									'url' => URL::route( 'dashboard.blog.destroy' , $blog->id),
									'class' => 'form-delete' 
									)
								) 
								!!}
								{!! Form::hidden('_method', 'DELETE') !!}
								<button type="submit" class="btn btn-sm btn-danger fa fa-times delete" data-toggle="tooltip" data-original-title="Delete">
								</button>
								{!! Form::close() !!}

							</td>
						</tr>
						@endforeach
						@else
						<tr>
							<td colspan="6" class="text-center">No data found</td>
						</tr>
						@endif

					</tbody>
				</table>
			</div>
			<!-- /.box-body -->
			<div class="box-footer clearfix">
				
				<div class="col-sm-8">
					@if( count($blogs) > 0 )
					Showing  {{ $blogs->firstItem() }} to {{ $blogs->lastItem() }} of {{ $blogs->total() }} entries
					@endif
				</div>

				<div class="col-sm-4">					
					<ul class="pagination pagination-sm no-margin pull-right">
						{{ $blogs->links() }}
					</ul>
				</div>

			</div>
		</div>
		<!-- /.box -->
	</div>
</div>

@endsection

modules/Cms/Resources/views/blog/backend/update.blade.php
@extends('backend.layout')

@section('title', 'Edit Blog')

@section('content')

<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">Edit Blog</h3>				
			</div>
			<!-- /.box-header -->

			<div class="box-body no-padding">
				{{ Form::model($blog, array('route' => array('dashboard.blog.update', $blog->id) , 'method' => 'PUT')) }}    

					<span class="col-md-4 col-lg-4">
					<div class="form-group">
						<!-- title -->
						{{ Form::label('title', 'Title') }}
						{{ Form::text('title', null , array( 'class' => 'form-control' ) ) }}      
					</div>
					</span>

					<span class="col-md-4 col-lg-4">
					<div class="form-group">
						<!-- category -->						
						{{ Form::label('type', 'Type') }}
						{!! Form::select('type', $blog_types, null , array( 'class' => 'form-control', 'id' => 'blog_type' )) !!}
						</div>					
					</span>

					<span class="col-md-4 col-lg-4">
					<div class="form-group">
						<!-- url -->
						{{ Form::label('url', 'Url') }}
						{{ Form::text('url', null , array( 'class' => 'form-control', 'placeholder' => '/aboutus' ) ) }}      
					</div>					
					</span>

					<span class="col-md-12 col-lg-12">
					<div class="form-group">
						<!-- content -->
						{{ Form::label('content', 'Content') }}
						{{ Form::textarea('content', null, array( 'class' => 'form-control', 'id' => 'mytextarea' ) ) }}
					</div>
					</span>

				<span class="col-md-6 col-lg-6">

					<p>
					  <h5>Meta Info.</h5> 
					  <div class="form-group">
						<!-- meta_desc -->
						{{ Form::label('meta_desc', 'Meta description') }}
						{{ Form::text('meta_desc', null, array( 'class' => 'form-control' ) ) }}
					  </div> 
					  <div class="form-group">
						<!-- meta_key -->
						{{ Form::label('meta_key', 'Meta keywords') }}
						{{ Form::text('meta_key', null, array( 'class' => 'form-control' ) ) }}
					  </div> 
					  <div class="form-group">
						<!-- meta_robot -->
						{{ Form::label('meta_robot', 'Meta robots') }}
						{{ Form::text('meta_robot', null, array( 'class' => 'form-control' ) ) }}
					  </div> 
					</p>
				</span>

				<span class="col-md-6 col-lg-6">
					
					<span class="blog_type_image">
					  <h5>Image Info.</h5>          
					  <div class="form-group">
						<!-- featured_image_title -->
						{{ Form::label('featured_image_title', 'Image title') }}
						{{ Form::text('featured_image_title', null, array( 'class' => 'form-control' ) ) }}
					  </div> 
					  <div class="form-group">

						<!-- featured_image -->
						{{ Form::label('Image', 'Image') }}

						<div class="input-group">
						<span class="input-group-btn">
						 <a id="lfm-image" data-input="thumbnail-image" data-preview="holder-image" class="btn btn-primary">
						   <i class="fa fa-picture-o"></i> Choose
						 </a>
						</span>
						{{ Form::hidden('featured_image', null, array( 'class' => 'form-control', 'id' => 'thumbnail-image' ) ) }}
						</div>
						<img id="holder-image" style="margin-top:15px;max-height:100px;" 
						<?php echo $blog->featured_image ? "src='".url($blog->featured_image)."'": '';?>>
					  </div>
					</span>

					<span class="blog_type_video" hidden>
					  <h5>Video Info.</h5>          


						<div class="form-group">
						<!-- vdo_title -->
						{{ Form::label('video_title', 'Video title') }}
						{{ Form::text('video_title', null, array( 'class' => 'form-control' ) ) }}
						</div> 

					  <div class="form-group">

						<!-- featured_image -->
						{{ Form::label('Video', 'Video') }}

						<div class="input-group">
						<span class="input-group-btn">
						 <a id="lfm-video" data-input="thumbnail-video" data-preview="holder-video" class="btn btn-primary">
						   <i class="fa fa-picture-o"></i> Choose
						 </a>
						</span>
						{{ Form::hidden('video', null, array( 'class' => 'form-control', 'id' => 'thumbnail-video') ) }}
						</div>
						<iframe id="holder-video" style="margin-top:15px;max-height:100px;" 
						<?php echo $blog->video ? "src='".url($blog->video)."'": '';?> 
						frameborder="0" class="video_preview" width="320" height="240"></iframe>

					  </div>
					  	
					  <div class="form-group">
						OR 
						<!-- video_url -->
						{{ Form::label('video_url', 'Video url') }}
						{{ Form::text('video_url', null, array( 'class' => 'form-control' ) ) }}

						<video width="320" height="240" style="margin-top:15px;max-height:100px;" controls>
						  <source src="<?php echo $blog->video_url ? : '';?>" type="video/mp4">
						  <source src="<?php echo $blog->video_url ? : '';?>" type="video/webm">
						  <source src="<?php echo $blog->video_url ? : '';?>" type="video/ogg">
						  Your browser does not support the video tag.
						</video>

					  </div>
					  	
					  <div class="form-group">
						OR <!-- video_embed -->
						{{ Form::label('video_embed', 'Video Embed') }}
						{{ Form::textarea('video_embed', null, array( 'class' => 'form-control', 'rows' => '3') ) }}
					  </div>					  
					</span>   

					<span class="blog_type_gallery" hidden>
					  <h5>Image Info.</h5>          
					  <div class="form-group">
						<!-- featured_image_title -->
						{{ Form::label('featured_image_title', 'Image title') }}
						{{ Form::text('featured_image_title', null, array( 'class' => 'form-control' ) ) }}
					  </div> 
					  <div class="form-group">

						<!-- featured_image -->
						{{ Form::label('Gallery Image', 'Gallery Image') }}

						<div class="input-group">
						<span class="input-group-btn">
						 <a id="lfm-image-gallery" data-input="thumbnail-image" data-preview="holder-image-gallery" class="btn btn-primary">
						   <i class="fa fa-picture-o"></i> Choose More
						 </a>
						</span>
						</div>
						

					  </div>
					</span>
				</span>

			</div>

			<!-- /.box-body -->
			<div class="box-footer clearfix">
					{{ Form::submit('Save', array( 'class' => 'btn btn-primary' )) }}
					{{ Form::close() }}
					<a href=" {{ route( 'dashboard.blog.index' ) }}" class="btn btn-default"/>Cancel</a>				
			</div>

		</div>
		<!-- /.box -->
	</div>
</div>
<script type="text/javascript">
	var blog_edit_or_create = true;
	var blog_gallery_images = JSON.parse('<?php echo isset($images)?$images:'[]';?>');
</script>
@endsection